version: '3.1'
services:
  db:
    image: postgres:9.2.10 # Clever Cloud version of postgres is 9.2.8
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: competence-center

  adminer:
    image: adminer
    ports:
      - 8088:8080