version: '3.1'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: competence-center
#      POSTGRES_INITDB_ARGS: dump.sql
#    volumes:
#      - /dump:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    ports:
      - 8088:8080